#!/bin/bash -l
#SBATCH -A uppmax2026-1-61
#SBATCH -p pelle
#SBATCH -n 1
#SBATCH -t 01:00:00
#SBATCH -J mummer_BLASTn
#SBATCH --output=%x.%j.out

module load MUMmer/4.0.1-GCCcore-13.3.0

#run alignment
nucmer \
/home/aida82/genome_project/analysis/5_BLASTn/complete_genomeBLASTn.fasta \
/home/aida82/genome_project/analysis/2_Canu_GenomeAssembly_PacBio/E745.contigs.fasta \
-p E745_vs_ref

#reads alignment files generated by nucmer and filters them
delta-filter -1 E745_vs_ref.delta > E745_vs_ref.filtered.delta

#create plot
mummerplot \
--png \
--layout \
-p E745_plot \
E745_vs_ref.filtered.delta
